const DAMAGE_TYPE = {
    SLASHING_DAMAGE: 'SLASHING_DAMAGE',
    PIERCING_DAMAGE: 'PIERCING_DAMAGE',
    FIRE_DAMAGE: 'FIRE_DAMAGE',
    FROST_DAMAGE: 'FROST_DAMAGE',
    EARTH_DAMAGE: 'EARTH_DAMAGE',
    LIGHTNING_DAMAGE: 'LIGHTNING_DAMAGE',
    FORCE_DAMAGE: 'FORCE_DAMAGE',
    HEALING: 'HEALING',
    NATURE_DAMAGE: 'NATURE_DAMAGE',
}

export default DAMAGE_TYPE